# Generated by Django 2.0.9 on 2018-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_auth_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alipay Authorization'),
        ),
    ]
